// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using costa_serena_grand_hotel_API.Data;

#nullable disable

namespace costa_serena_grand_hotel_API.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    partial class HotelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("costa_serena_grand_hotel_API.Models.Foglalas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Meddig")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Mettol")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SzobaId")
                        .HasColumnType("int");

                    b.Property<int>("VendegId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SzobaId");

                    b.HasIndex("VendegId");

                    b.ToTable("foglalas");
                });

            modelBuilder.Entity("costa_serena_grand_hotel_API.Models.Szoba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Alapterulet")
                        .HasColumnType("double");

                    b.Property<int>("Emelet")
                        .HasColumnType("int");

                    b.Property<string>("Szam")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.ToTable("szoba");
                });

            modelBuilder.Entity("costa_serena_grand_hotel_API.Models.Vendeg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Fizetett")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Hazszam")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("IranyitoSzam")
                        .HasColumnType("int");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SzemelyiIgazolvanySzam")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Utca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Varos")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("vendeg");
                });

            modelBuilder.Entity("costa_serena_grand_hotel_API.Models.Foglalas", b =>
                {
                    b.HasOne("costa_serena_grand_hotel_API.Models.Szoba", "Szoba")
                        .WithMany("Foglalasok")
                        .HasForeignKey("SzobaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("costa_serena_grand_hotel_API.Models.Vendeg", "Vendeg")
                        .WithMany("Foglalasok")
                        .HasForeignKey("VendegId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Szoba");

                    b.Navigation("Vendeg");
                });

            modelBuilder.Entity("costa_serena_grand_hotel_API.Models.Szoba", b =>
                {
                    b.Navigation("Foglalasok");
                });

            modelBuilder.Entity("costa_serena_grand_hotel_API.Models.Vendeg", b =>
                {
                    b.Navigation("Foglalasok");
                });
#pragma warning restore 612, 618
        }
    }
}
